### ISSUE TITLE
Cannot connect to database

### ISSUE THREAD

**Issue by hugo50** [ethicalhack3r/DVWA#67]
Could not connect to the database.
Please check the config file.

This is error message I am receiving from DVWA.  I am using XAMMP v 5.6.19-0.  I have the password in the config file set to '', using root as username.  I have looked for a solution to the issue but I appear to be on my own on this one.  I am running OSX 10.11.3 Not sure what else to tell you Thanks for any help,
Charles

**Comment by digininja** [comment]
Is the mysql root users password blank?

**Comment by hugo50** [comment]
As near as I can tell. In the MySQL config file it is listed as blank

**Comment by digininja** [comment]
You don't set the password in the config file, it is set in the database
itself. Try to connect to the database with a blank password and I bet it
doesn't work.

You need to find or reset your database password then put that in the dvwa
config file.

**Comment by hugo50** [comment]
Finally got it working.  :)  
Not sure why but when I changed 
$_DVWA[ ‘db_server’ ] from 127.0.0.1 to localhost 
everything suddenly worked.
Thanks for the help.
Happy Hacking
Charles

**Comment by mike-bailey** [comment]
Resolved

**Comment by neilcorrea** [comment]
Hi all,

I've run into this issue as well.  I've changed the database port to 3306; I've tried using localhost; I've made the password blank and still have the Could not connect to the MySQL service.
Please check the config file.

My config file looks like this:
#   Please use a database dedicated to DVWA.
$_DVWA = array();
#$_DVWA[ 'db_server' ]   = '127.0.0.1';
$_DVWA[ 'db_server' ]   = 'localhost';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ]     = 'root';
$_DVWA[ 'db_password' ] = '';

# Only used with PostgreSQL/PGSQL database selection.
$_DVWA[ 'db_port '] = '3306';
#$_DVWA[ 'db_port '] = '5432';

I can login to mysql with the following command: 
root@dvwa:/var/www/html/DVWA/config# mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.18-0ubuntu0.17.04.1 (Ubuntu)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

Even if I use the -p flag to prompt for password, I can hit enter and it lets me in.  Could this be a permissions issue?  I know if I login to linux with a non-root user and try to connect to mysql as root I get a connection error.

I'm not seeing an error when I do a tail -f /var/log/apache2/error.log appear when I click on the Create/Reset database.

Setup Check

Operating system: *nix
Backend database: MySQL
PHP version: 5.6.30-12~ubuntu17.04.1+deb.sury.org+1

Web Server SERVER_NAME: 40.121.214.111

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module gd: Installed
PHP module mysql: Installed
PHP module pdo_mysql: Installed

MySQL username: root
MySQL password: *blank*
MySQL database: dvwa
MySQL host: localhost

reCAPTCHA key: Missing

[User: root] Writable folder /var/www/html/DVWA/hackable/uploads/: Yes
[User: root] Writable file /var/www/html/DVWA/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

Status in red, indicate there will be an issue when trying to complete some modules.

**Comment by mike-bailey** [comment]
Hey @neilcorrera, what happens when you run "USE dvwa;" in mysql?

**Comment by mike-bailey** [comment]
^ Sorry for the typo, on mobile

**Comment by neilcorrea** [comment]
I haven't created the database yet.  I'm assuming the Create/Reset button would do that.  In a past install, I did create the db manually, but ran into the same issue.

**Comment by mike-bailey** [comment]
I believe it only populates tables. Do you mind creating the DB and trying again?

**Comment by digininja** [comment]
Didn't I already give the answer and you just confirmed it? You can't
connect as database root unless you are system user root. As Apache doesn't
run as root you can't use the root user in DVWA. You need to create a new
database user and use that, the command is in the issue.

**Comment by mike-bailey** [comment]
Is this new? I've logged in as root with Apache using www-data before....
   
 
   
 
 
>  
>  
>  
>      
>    
>  
>

**Comment by neilcorrea** [comment]
mysql> create database dvwa;
Query OK, 1 row affected (0.00 sec)

mysql> show grants;
+---------------------------------------------------------------------+
| Grants for root@localhost                                           |
+---------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION |
| GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION        |
+---------------------------------------------------------------------+
2 rows in set (0.00 sec)

root@dvwa:/var/www/html/DVWA/config# service apache2 restart
root@dvwa:/var/www/html/DVWA/config# service mysql restart

Same error.

**Comment by digininja** [comment]
It's a mariadb thing and that is the default on Kali which a lot of people
end up using dvwa with.

**Comment by mike-bailey** [comment]
Maybe try what @digininja said?

**Comment by neilcorrea** [comment]
Sorry digininja I must have missed that.  I looked into many threads and the answer typically was change the password to "".  The default install has the user as root so I made a bad assumption.  I will try that now.

**Comment by neilcorrea** [comment]
Awesome.  Thank you.  That took care of it.  I did the following:
mysql> create user 'dvwauser'@'localhost' IDENTIFIED BY '';
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT ALL PRIVILEGES ON *.* to 'dvwauser'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)

mysql> quit

Then, changed the user in the config.inc.php file.

**Comment by digininja** [comment]
Maybe it was a different ticket that it was on.

Took me a while to find it as it is mariadb specific and you can't see it
unless you create a non root user then try to connect as root.

**Comment by KlausAlfred** [comment]
$_DVWA = array();
#$_DVWA[ 'db_server' ] = '127.0.0.1';
$_DVWA[ 'db_server' ] = 'localhost';
$_DVWA[ 'db_database' ] = 'dvwa';
$_DVWA[ 'db_user' ] = 'root';
$_DVWA[ 'db_password' ] = ''; // this password most need be the same of the root user of your DB.

**Comment by mike-bailey** [comment]
@KlausAlfred If you are having issues please open an issue of your own and describe your issue.

**Comment by kpomeroy1979** [comment]
Hi guys,

I got confused on which config.inc file to edit. I was making changes in the wrong file so obviously the db setup wasnt working. 

The fix for me was easy.

The issue I had was the fact that I was editing config.inc.**PHP**. You have to edit DVWA-Master\config\config.**INC** and set the root password to nothing aka '' (these are ' and ' characters and not the quotatation mark ")

**Comment by digininja** [comment]
I'm guessing you are on Windows with displaying file extensions turned off.
You need to copy config.inc.php.dist to config.inc.php and then edit the
new file.

**Comment by kpomeroy1979** [comment]
Yes that is correct. I set it up on Windows and did rename the config file when setting up as I didn’t have the extensions displayed I was working on the wrong file. :)
